#!/usr/bin/env bash
# This script is displaying the story of passwd

while IFS=":" read u pw uid gid gecos h s
do
	echo "The user $u is part of the $gid gang, lives in $h and rides $s. $uid's place is protected by the passcode $pw, more info about the user here: $gecos"

done < "/etc/passwd"
