#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and in ninth iteration print Hi
i=1

while [ $i -lt 10 ]
do
   if [ $i == 9 ]
   then
      echo "Hi"
   fi
   echo "Holberton School"   
   i=$(( i + 1 ))
done
